import React, { createContext, useContext, useState, useCallback, useEffect } from 'react';

/**
 * ─── Lead object shape ──────────────────────────────────────────────────────
 * @typedef {Object} Lead
 * @property {string}  id        - Unique UUID generated by crypto.randomUUID()
 * @property {string}  name      - Full name of the contact
 * @property {string}  company   - Company / organisation name
 * @property {string}  email     - Contact email address
 * @property {string}  phone     - Contact phone number (optional)
 * @property {'New'|'Contacted'|'Meeting Scheduled'|'Proposal Sent'|'Won'|'Lost'} status
 * @property {'Website'|'Referral'|'LinkedIn'|'Cold Call'|'Email Campaign'|'Other'} source
 * @property {string}  createdAt - ISO-8601 timestamp set automatically on create
 */

export const LeadContext = createContext(null);

export function LeadProvider({ children }) {
  const [leads, setLeads] = useState(() => {
    try {
      const stored = localStorage.getItem('crm_leads');
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  });

  const [notifications, setNotifications] = useState(() => {
    try {
      const stored = localStorage.getItem('crm_notifications');
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('crm_leads', JSON.stringify(leads));
      localStorage.setItem('crm_notifications', JSON.stringify(notifications));
    } catch {
      // Ignore write errors
    }
  }, [leads, notifications]);

  const addNotification = useCallback((message, type) => {
    const newNotif = {
      id: crypto.randomUUID(),
      message,
      type,
      isRead: false,
      createdAt: new Date().toISOString(),
    };
    setNotifications((prev) => [newNotif, ...prev]);
  }, []);

  const markNotificationsAsRead = useCallback(() => {
    setNotifications((prev) => prev.map(n => ({ ...n, isRead: true })));
  }, []);

  const clearNotifications = useCallback(() => {
    setNotifications([]);
  }, []);

  /**
   * Adds a new lead.
   * Generates a unique ID and createdAt timestamp.
   * @param {Omit<Lead, 'id' | 'createdAt'>} formData 
   */
  const addLead = useCallback((formData) => {
    const newLead = {
      ...formData,
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
    };
    setLeads((prev) => [newLead, ...prev]);
    addNotification(`New lead added: ${formData.name}`, 'add');
  }, [addNotification]);

  /**
   * Updates an existing lead by its id.
   * @param {string} id 
   * @param {Partial<Lead>} changes 
   */
  const updateLead = useCallback((id, changes) => {
    setLeads((prev) => {
      const oldLead = prev.find(l => l.id === String(id));
      if (oldLead && changes.status && oldLead.status !== changes.status) {
        if (changes.status === 'Won') {
          addNotification(`Lead converted: ${changes.name || oldLead.name}`, 'convert');
        } else if (changes.status === 'Lost') {
          addNotification(`Lead lost: ${changes.name || oldLead.name}`, 'loss');
        } else {
          addNotification(`Lead updated: ${changes.name || oldLead.name}`, 'update');
        }
      } else if (oldLead) {
        addNotification(`Lead updated: ${changes.name || oldLead.name}`, 'update');
      }
      return prev.map((l) => (l.id === String(id) ? { ...l, ...changes } : l));
    });
  }, [addNotification]);

  /**
   * Deletes a lead by its id.
   * @param {string} id 
   */
  const deleteLead = useCallback((id) => {
    setLeads((prev) => prev.filter((l) => l.id !== String(id)));
  }, []);

  /**
   * Gets a lead by its id.
   * @param {string} id 
   */
  const getLeadById = useCallback(
    (id) => leads.find((l) => l.id === String(id)),
    [leads]
  );

  const value = {
    leads,
    addLead,
    updateLead,
    deleteLead,
    getLeadById,
    notifications,
    markNotificationsAsRead,
    clearNotifications,
  };

  return <LeadContext.Provider value={value}>{children}</LeadContext.Provider>;
}

/**
 * Hook to use the LeadContext
 * @returns {Object} { leads, addLead, updateLead, deleteLead, getLeadById }
 */
export function useLeads() {
  const ctx = useContext(LeadContext);
  if (ctx === null) {
    throw new Error('useLeads must be called inside a LeadProvider');
  }
  return ctx;
}
